version: '3'
services:
    app:
        build: .
        environment:
            - COMPOSER_HOME=app/composer
            - COMPOSER_CACHE_DIR=app/composer/cache
            - DB_CONNECTION=mongodb
            - DB_HOST=${MONGO_HOST}
            - DB_PORT=${MONGO_PORT}
            - DB_DATABASE=${MONGO_DB}
            - DB_USERNAME=${MONGO_USER}
            - DB_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - .:/app
        ports:
            - "9000:9000"
        depends_on:
            - mongo

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
